version: '3.3'
services:
  db-main:
    extends:
      file: common.yml
      service: db
    environment:
      MYSQL_DATABASE: 'readinglist'
    ports:
      - '3306:3306'
    volumes:
      - my-db-main:/var/lib/mysql

  db-test:
    extends:
      file: common.yml
      service: db
    environment:
      MYSQL_DATABASE: 'readinglist'
    ports:
      - '3307:3306'
    volumes:
      - my-db-test:/var/lib/mysql

volumes:
  my-db-main:
  my-db-test:
